server:
  port: ${AUTH_SERVICE_PORT}

spring:
  application:
    name: auth-service
  datasource:
    url: ${AUTH_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  refresh:
    expiration: ${JWT_REFRESH_EXPIRATION}
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
