version: "3.8"

services:
  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8081:8081" # for portfolio demo purposes
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: transaction-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: