services:
  transaction-service:
    build: ./transaction-service
    container_name: transaction-service
    ports:
      - "8081:8081"
    depends_on:
      - transaction-db
    env_file:
      - .env
    networks:
      - app-network

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8082:8082"
    depends_on:
      - auth-db
    env_file:
      - .env
    networks:
      - app-network

  transaction-db:
    image: postgres:15
    container_name: transaction-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${TRANSACTION_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - transaction_data:/var/lib/postgresql/data
    networks:
      - app-network

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  transaction_data:
  auth_data: