server:
  port:8081

spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5432/db_name
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  profiles:
    active: dev