server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**
        - id: transaction-service
          uri: http://transaction-service:8081
          predicates:
              - Path=/transactions/**