spring:
  application:
    name: discovery-service

service:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
        
logging:
  level:
    com.netflix.eureka: INFO
    org.springframework: INFO